# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  deploy-beta-job:
    name: Deploy FIAP Cloud API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          ref: master
          node-version: 12

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.FIAP_SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.FIAP_KNOWN_HOSTS }}
          # config: ${{ secrets.CONFIG }} # ssh_config; optional

      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: "ubuntu@ec2-54-157-139-9.compute-1.amazonaws.com"
          privateKey: ${{ secrets.FIAP_SSH_KEY }}
          command: |
            pm2 list
            cd backend
            git pull
            yarn
            pm2 restart 0
